DROP ROLE IF EXISTS iot_admin;
CREATE USER IF NOT EXISTS iot_admin WITH password 'admin';

CREATE DATABASE iot_event_db owner iot_admin;

\c iot_event_db;

CREATE TABLE IF NOT EXISTS IOT_EVENT_DATA (
 ID SERIAL PRIMARY KEY,
 TEMPERATURE SERIAL NOT NULL UNIQUE,
 HUMIDITY SERIAL NOT NULL,
 BATTER_LEVEL SERIAL NOT NULL,
 CREATED_BY VARCHAR(100) NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100) NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS IOT_EVENT (
 ID SERIAL PRIMARY KEY,
 DEVICE_ID VARCHAR(20) NOT NULL UNIQUE,
 EVENT_TYPE VARCHAR(20) NOT NULL,
 DATE_TIME TIMESTAMP NOT NULL UNIQUE,
 EVENT_DATA_ID SERIAL,
 CREATED_BY VARCHAR(100) NOT NULL,
 CREATED_DATE TIMESTAMP NOT NULL,
 UPDATED_BY VARCHAR(100) NOT NULL,
 UPDATED_DATE TIMESTAMP NOT NULL,

 FOREIGN KEY (EVENT_DATA_ID) REFERENCES IOT_EVENT_DATA(ID)
);